config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  scope "/(:locale)", locale: /fr/ do

  	root "pages#home", as: "home_page"

    resource :profile

  	resource :agency, only: :show

  	resources :agencies, only: [:index, :show, :edit] do
  		resources :properties
  	end

  	get "agency/benefits", to: "pages#benefits_for_agency", as: "agency_benefits"

  	get "about_us", to: "pages#about_us", as: "about_us"

  	get "contact_us", to: "pages#contact_us", as: "contact_us"

  	get "faq", to: "pages#faq", as: "faq"

  	get "pricing_plan", to: "pages#pricing_plan", as: "pricing_plan"

  	get "terms_and_conditions", to: "pages#terms_and_conditions", as: "terms_and_conditions"

  	post 'properties/:id/publish', to: 'properties#publish', as: "publish_property"

  	post 'properties/:id/deactivate', to: 'properties#deactivate', as: "deactivate_property"

    resources :properties

    resources :messages, only: :create

    resources :contacts, only: :create

    resources :newsletters, only: :create

    scope "/dashboard" do
      resources :my_properties, only: [:index, :edit, :destroy]
    end

  end

end

app/models/ad_type.rb
class AdType < ApplicationRecord
	has_many :properties
end

app/models/agency.rb
class Agency < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    belongs_to :user
    has_many :properties
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :properties
end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :first_name, :last_name, :phone_number, :email, :message, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :user
    validates :name, :phone, :email, :message, :user_id, presence: true
end

app/models/newsletter.rb
class Newsletter < ApplicationRecord
    validates :email, presence: true
    validates :email, uniqueness: { message: "L'adresse email existe déja !" }

    before_save :downcase_email
    # after_save :subscribe

    def downcase_email
        self.email = email.downcase
    end

    # def subscribe
    #     gibbon = Gibbon::Request.new(api_key: Rails.application.secrets.mailchimp_api_key)
    #     list_id = Rails.application.secrets.mailchimp_list_id_key
    #     begin
    #   gibbon.lists(list_id).members.create(
    #   body: {
    #     email: self.email,
    #     status: "subscribed"
    #   })
    # rescue Gibbon::MailChimpError => e
    #   puts "Try Again: #{e.message} ‐ #{e.raw_body}"
    # end
    # end
end

app/models/property.rb
class Property < ApplicationRecord
    extend FriendlyId
    friendly_id :title, use: :slugged

    FEATURE = ["Electricité", "Eau", "WC", "Internet"].sort
    ETAGE = ["Rez-de-chaussée", "1er étage", "2ème étage", "3ème étage", "4ème étage", "5ème étage", "6ème étage", "7ème étage"].sort
    AVAILABLE = { Oui: :TRUE, Nom: :FALSE }

    belongs_to :user
    belongs_to :city
    belongs_to :ad_type
    belongs_to :property_type
    belongs_to :room
    # belongs_to :agency

    validates :price, :description, :address, :area, :title, presence: true
    validates :etage, presence: true, allow_blank: true
    validates :available, presence: true, inclusion: { in: ["TRUE", "FALSE"] }, allow_blank: true
    validates :title, uniqueness: true
    validates :area, numericality: { only_integer: true }
    validates :deposit, numericality: { only_integer: true, greeter_than_or_egal_to: 0 }, allow_blank: true
    validates_associated :user

    has_many_attached :images, dependent: :purge

    scope :published, -> { where(published: true) }
    scope :unpublished, -> { where(published: false) }

    before_save :mettre_tout_en_minuscule
    before_create :definir_la_date_dexpiration
    after_create :suprimer_si_annonce_expire
    # after_destroy :suprimer_les_photos


    private

    def mettre_tout_en_minuscule
        self.title.downcase!
        self.description.downcase!
        self.address.downcase!
    end

    def definir_la_date_dexpiration
        self.published_at = Date.today
        self.expire_at = Date.today + 2.weeks
    end

    def suprimer_si_annonce_expire
        p = Property.find(self.id)
        if p.published? && p.expire_at.past?
            p.delete
        end
    end

    # def suprimer_les_photos
    #     self.images.purge
    # end

end

app/models/property_type.rb
class PropertyType < ApplicationRecord
	has_many :properties
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :properties
end

app/models/user.rb
class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
    devise :confirmable
    devise :omniauthable, omniauth_providers: %i[facebook]

    ROLE = ["Agent immobilier", "Propriétaire"].sort
    GENDER = { M: :Male, F: :Female }

    # validates :role, presence: true, on: :update
    validates :first_name, :last_name, :phone_number, presence: true, on: :update
    validates :phone_number, uniqueness: true, numericality: { only_integer: true }, length: { is: 8 }, on: :update

    # before_create :create_administrator
    after_create :send_welcome_email
    # after_destroy :suprimer_photo_de_profile
    # after_create :build_agency_or_profile

    # has_one :agency, dependent: :delete
    has_many :properties, dependent: :delete_all
    has_many :messages
    has_one_attached :profile_picture, dependent: :purge

    def self.from_omniauth(auth)
        where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
            user.email = auth.info.email
            user.password = Devise.friendly_token[0,20]
            # user.name = auth.info.name   # assuming the user model has a name
            # user.image = auth.info.image # assuming the user model has an image

            user.profile_picture = auth.info.picture
            user.first_name = auth.info.first_name
            user.last_name = auth.info.last_name

            # user.token = auth.credentials.token
            # user.token_expires_at = Time.at(auth.credentials.expires_at)

            # If you are using confirmable and the provider(s) you use validate emails,
            # uncomment the line below to skip the confirmation emails.
            user.skip_confirmation!
        end
    end

    def self.new_with_session(params, session)
        super.tap do |user|
            if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
                user.email = data["email"] if user.email.blank?
            end
        end
    end

    private

    def send_welcome_email
        UserMailer.welcome(self).deliver_now
    end

    # def suprimer_photo_de_profile
    #     self.profile_picture.purge if self.profile_picture.present?
    # end

    def create_administrator
        if self.email == "francel.webdev@gmail.com"
            self.admin = true
        end
    end

    # def build_agency_or_profile
    #   if self.role == "Agent immobilier"
    #       Agency.create user_id: self.id
    #   end
    # end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    skip_before_action :authenticate_user!

    def home

    end

    def contact_us
        @contact = Contact.new
    end

    def faq

    end

    def terms_and_conditions

    end

    def benefits_for_agency

    end

    def benefits_for_owner

    end

    def pricing_plan

    end

end

app/helpers/agencies_helper.rb
module AgenciesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper    
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/pages/about_us.html.erb
<% content_for :page_title, "A propos de nous" %>

<section class="container-fluid py-5">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h3>Page en construction</h3>
                <p><%= image_tag "ajax-loader.gif" %></p>
                <p>Restez connecté avec nous. Inscrivez-vous à la newsletter pour recevoir des annonces et informations fraîches.</p>
            </div>
        </div>
    </div>
</section>

app/views/pages/faq.html.erb
<% content_for :page_title, "FAQ" %>

app/views/pages/home.html.erb
<% content_for :page_title, "Annonces immobiliers au Bénin" %>
<% content_for :page_meta_description, "" %>
<% content_for :page_meta_keywords, "" %>
<% content_for :Morphext do %>
<script>
$(function() {
$("#js-rotating").Morphext({
    animation: "bounceIn", // Overrides default "bounceIn"
    speed: 3000, // Overrides default 2000
    complete: function () {
        // Overrides default empty function
    }
});
});
</script>
<% end %>

<div class="jumbotron jumbotron-fluid d-flex align-items-center mb-0 jumbotron-accueil py-5">
    <div class="container">
        <h1 class="text-white text-center mb-3">Trouver <span id="js-rotating" class="font-weight-bold">la chambre, la maison, le villa, l'appartement, le bureau, la boutique, le magasin, le parcelle, le terrain</span> de vos rêves sans aucune difficulté.</h1>
        <div class="py-3 px-3 rounded" style="background-color: rgba(0, 0, 0, 0.3)">
            <%= form_with url: properties_path, method: :get, local: true do |f| %>
            <div class="form-row">
                <div class="col-md-3 px-0 mb-2">
                    <%= f.collection_select :property_type, PropertyType.all, :name, :name, { prompt: "Type de bien" }, { class: "rounded-0 form-control form-control-lg", required: true } %>
                </div>
                <div class="col-md-3 px-0 mb-2">
                    <%= f.collection_select :ad_type, AdType.all, :name, :name, { prompt: "Type d'annonce" }, { class: "rounded-0 form-control form-control-lg", required: true } %>
                </div>
                <div class="col-md-4 px-0 mb-2">
                    <%= f.text_field :city, placeholder: "Ou ? Ex: Fidjrossè, Abomey-Calavi", class: "rounded-0 form-control form-control-lg", required: true %>
                </div>
                <div class="col-md-2 px-0 mb-2">
                    <%= f.submit "Rechercher", class: "rounded-0 btn btn-primary btn-lg btn-block" %>
                </div>
            </div>
            <% end %>
        </div>
    </div>
</div>


<section class="py-5 sr-only">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center mb-5">
                <h3>Annonces en vedette</h3>
            </div>
            <div class="col-12">
                <div class="row annonce_nouvellement_publié">
                    <div class="col-12 col-md-4 mx-1">
                        <div class="card mb-4">
                            <img class="card-img-top" src="" alt="Card image cap">
                            <div class="card-body">
                                <h5 class="card-text">Appartement</h5>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                                        <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                                    </div>
                                    <small class="text-muted">9 mins</small>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="py-5 bg-white">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center mb-2">
                <h2>Comment ça marche ?</h2>
            </div>
            <div class="col-lg-4 text-center mb-4 d-flex flex-column justify-content-between">
                <i class="fa fa-search fa-5x text-primary" aria-hidden="true"></i>
                <p>Faîte une recherche et choisissez un bien parmis les résultats de recherche.</p>
            </div>
            <div class="col-lg-4 text-center mb-4 d-flex flex-column justify-content-between">
                <i class="fa fa-mobile fa-5x text-primary" aria-hidden="true"></i>
                <p>Contacter le propriétaire du bien pour convenir d'un RDV pour la visite.</p>
            </div>
            <div class="col-lg-4 text-center mb-4 d-flex flex-column justify-content-between">
                <i class="fa fa-thumbs-o-up fa-4x text-primary" aria-hidden="true"></i>
                <p>Visiter le bien puis régler l'avance et prenez les clefs si le bien correspond à vos besoins.</p>
            </div>
        </div>
    </div>
</section>

<section class="py-5 sr-only">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center mb-5">
                <h2>Communes/Quartiers les plus consultés</h2>
            </div>
            <div class="col-lg-8 mb-5">
                <%= link_to home_page_path, class: "sans-text-decoration" do %>
                <div class="card">
                    <div class="card-body text-center">
                        <h2 class="card-title mb-0">Cotonou</h2>
                        <p class="lead">N* de biens</p>
                    </div>
                </div>
                <% end %>
            </div>
            <div class="col-lg-4 mb-5">
                <%= link_to home_page_path, class: "sans-text-decoration" do %>
                <div class="card">
                    <div class="card-body text-center">
                        <h2 class="card-title mb-0">Cotonou</h2>
                        <p class="lead">N* de biens</p>
                    </div>
                </div>
                <% end %>
            </div>
            <div class="col-lg-4 mb-5">
                <%= link_to home_page_path, class: "sans-text-decoration" do %>
                <div class="card">
                    <div class="card-body text-center">
                        <h2 class="card-title mb-0">Cotonou</h2>
                        <p class="lead">N* de biens</p>
                    </div>
                </div>
                <% end %>
            </div>
            <div class="col-lg-8 mb-5">
                <%= link_to home_page_path, class: "sans-text-decoration" do %>
                <div class="card">
                    <div class="card-body text-center">
                        <h2 class="card-title mb-0">Cotonou</h2>
                        <p class="lead">N* de biens</p>
                    </div>
                </div>
                <% end %>
            </div>
        </div>
    </div>
</section>

<section class="py-5 bg-white sr-only">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center mb-4">
                <h2>Quelques agences immobiliers</h2>
            </div>
        </div>
    </div>
</section>

app/views/pages/pricing_plan.html.erb
<!-- #dee2e6
jusqu'à ce que vos biens soit loués ou vendus
-->

<section class="container-fluid py-5 bg-white">
	<section class="container">
		<div class="row">
			<div class="col-12 text-center mb-3">
				<h2>Nos tarifs</h2>
				<p class="lead"><span class="font-weight-bold h4">SICO</span> vous offre 3 différents tarifs pour répondre à vos besoins.</p>
			</div>
		</div>
        <section class="row d-flex align-items-center">
            <div class="col-lg-4 mb-4">
                <div class="card pricing_plan shadow-sm">
                    <div class="card-header text-center">
                        <h3 class="my-0">Basic</h3>
                    </div>
                    <div class="card-body text-center">
                        <h1 class="card-title">
                            Gratuit
                        </h1>
                        <hr>
                        <ul class="list-unstyled">
                            <li class="my-2">Annonces illimités.</li>
                            <li class="my-2">Durée d'affichage: 1 semaine.</li>
                            <li class="my-2">3 photos maximum/annonce.</li>
                        </ul>
                        <p>
                            <%= link_to "Choisir ce plan", new_property_path(pricing_plan_choosing: "basic"), class: "btn btn-outline-primary btn-lg" %>
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 mb-4">
                <div class="card pricing_plan shadow-sm">
                    <div class="card-header text-center">
                        <h3 class="my-0">Agence</h3>
                    </div>
                    <div class="card-body text-center">
                        <h1 class="card-title">
                            <%= number_with_delimiter(sprintf("%0.00f", 75000)) %><sup>f</sup><small class="text-muted">/mois</small>
                        </h1>
                        <hr>
                        <ul class="list-unstyled">
                            <li class="my-2">Annonces illimités.</li>
                            <li class="my-2">Durée d'affichage: illimité.</li>
                            <li class="my-2">12 photos maximum/annonce plus 1 vidéo.</li>
                            <li class="my-2">Téléchargements des modèles de contrats.</li>
                            <li class="my-2">Page vitrine pour présenter votre agence.</li>
                            <li>Assistance 24/7.</li>
                            <li class="my-2">Assistance juridique mis à votre disposition.</li>
                        </ul>
                        <p>
                            <%= link_to "Contactez-nous", contact_us_path, class: "btn btn-outline-primary btn-lg"  %>
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 mb-4">
                <div class="card border-primary pricing_plan shadow-sm">
                    <div class="card-header bg-primary text-center">
                        <h3 class="my-0 text-white">Profesionnel</h3>
                    </div>
                    <div class="card-body text-center">
                        <h1 class="card-title">
                            <%= number_with_delimiter(sprintf("%0.00f", 39500)) %><sup>f</sup><small class="text-muted">/mois</small>
                        </h1>
                        <hr>
                        <ul class="list-unstyled">
                            <li class="my-2">Annonces illimités.</li>
                            <li class="my-2">Durée d'affichage: 1 mois.</li>
                            <li class="my-2">6 photos maximum/annonce.</li>
                            <li class="my-2">Téléchargements des modèles de contrats.</li>
                            <li class="my-2">Assistance 24/7.</li>
                        </ul>
                        <p>
                            <%= link_to "Contactez-nous", contact_us_path, class: "btn btn-primary btn-lg"  %>
                        </p>
                    </div>
                </div>
            </div>

        </section>
	</section>
</section>

app/views/pages/terms_and_conditions.html.erb
<% content_for :page_title, "terms_and_conditions" %>

<section class="container-fluid">
	<section class="container">
		<section class="row">
			<div class="col-12 text-center p-5">
				<h1>Page en construction</h1>
				<p><%= image_tag "ajax-loader.gif" %></p>
			</div>
		</section>
	</section>
</section>

app/views/shareds/_dashboard_sidebar_menu.html.erb
<div class="card bg-white border-0">
    <div class="card-body">
        <h5 class="font-weight-bold mb-3">Tableau de bord</h5>
        <ul class="list-unstyled">
            <li class="my-2">
                <%= link_to "Mes biens", my_properties_path, class: "text-secondary" %>
            </li>
            <li class="my-2">
                <%= link_to "Mon profile", edit_user_registration_path, class: "text-secondary" %>
            </li>            
            <li class="my-2">
                <%= link_to "Publiez une annonce", new_property_path, class: "text-secondary" %>
            </li>
        </ul>
    </div>
</div>

app/views/shareds/_flash.html.erb
<% if notice %>
<div class="alert alert-success alert-dismissible fade show mb-0 rounded-0" role="alert">
    <p class="text-center mb-0"><i class="fa fa-thumbs-o-up fa-lg" aria-hidden="true"></i>&nbsp; <%= notice %></p>
	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
</div>
<% elsif alert %>
<div class="alert alert-danger alert-dismissible fade show mb-0 rounded-0" role="alert">
    <p class="text-center mb-0"><i class="fa fa-hand-o-right fa-lg" aria-hidden="true"></i>&nbsp; <%= alert %></p>
	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
</div>
<% end %>

app/views/shareds/_footer.html.erb
<footer class="pt-4 bg-white">
    <div class="container">
        <div class="row py-5">
            <div class="col-lg-4 my-3 my-lg-0">
                <h3 class="mb-3 font-weight-bold d-flex align-items-baseline">SICO</h3>
                <p>Nous aidons les gens a trouver le bien qui leurs correspond sans aucun difficulté.</p>
                <address>
                    <ul class="list-unstyled">
                        <li class="my-2">
                            <span class="font-weight-bold text-dark">96 61 90 73</span>
                        </li>
                        <li class="my-2">
                            <%= mail_to "francel.webdev@gmail.com", "francel.webdev@gmail.com", subject: "Demande d'information", class: "text-dark" %>
                        </li>
                    </ul>
                </address>
            </div>
            <div class="col-lg-2 my-3 my-lg-0">
                <h5 class="mb-3 font-weight-bold">A propos</h5>
                <ul class="list-unstyled">
                    <li class="my-2">
                        <%= link_to 'A propos de nous', about_us_path, class: "text-dark" %>
                    </li>
                    <li class="my-2">
                        <%= link_to 'Contactez nous', contact_us_path, class: "text-dark" %>
                    </li>
                    <li class="my-2">
                        <%= link_to "Recrutement", home_page_path, class: "text-dark" %>
                    </li>
                </ul>
            </div>
            <div class="col-lg-3 my-3 my-lg-0">
                <h5 class="mb-3 font-weight-bold">Informations</h5>
                <ul class="list-unstyled">
                    <li class="my-2">
                        <%= link_to "Nos tarifs", pricing_plan_path, class: "text-dark" %>
                    </li>
                    <li class="my-2">
                        <%= link_to "Blog", home_page_path, class: "text-dark" %>
                    </li>
                    <li class="my-2">
                        <%= link_to "Condition d'utilisation", home_page_path, class: "text-dark" %>
                    </li>
                    <li class="my-2">
                        <%= link_to "Confidentialité", home_page_path, class: "text-dark" %>
                    </li>
                    <li class="my-2">
                        <%= link_to "FAQ", home_page_path, class: "text-dark" %>
                    </li>
                </ul>
            </div>
            <div class="col-lg-3 my-3 my-md-0">
                <div class="row">
                    <div class="col-12 mb-4">
                        <h5 class="mb-3 font-weight-bold">Newsletter</h5>
                        <p class="text-dark"><small>Restez connecté avec nous. Inscrivez-vous à la newsletter pour recevoir des annonces et informations fraîches.</small></p>
                        <%= render "newsletters/newsletter_form" %>
                    </div>
                    <div class="col-12">
                        <h5 class="mb-3 font-weight-bold">Suivez-nous sur</h5>
                        <ul class="list-unstyled d-flex mt-4">
                            <li>
                                <%= link_to "https://facebook.com", class: "m-2", title: "Suivez-nous sur facebook" do %>
                                <%= image_tag "145797-social-network-logo-collection/svg/facebook.svg", alt: "Liens vers la page facebook de Sico", width: "30px;" %>
                                <i class="fab fa-facebook-f sr-only"></i>
                                <% end %>
                            </li>
                            <li>
                                <%= link_to "https://facebook.com", class: "m-2", title: "Suivez-nous sur twitter" do %>
                                <%= image_tag "145797-social-network-logo-collection/svg/twitter.svg", alt: "Liens vers la page twitter de Sico", width: "30px;" %>
                                <i class="fab fa-twitter sr-only"></i>
                                <% end %>
                            </li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
        <div class="row pt-3" style="border-top: 1px solid #dee2e6 !important;">
            <div class="col-lg-12 text-center">
                <p class="text-secondary">&copy; Copyright <%= @current_year %> Sico. Tous droit réservé.</p>
            </div>
        </div>
    </footer>

app/views/shareds/_navbar.html.erb
<% content_for :add_property do %>
<li class="nav-item mx-1">
    <li class="nav-item mx-1">
        <%= link_to "Déposer une annonce", new_property_path, class: "nav-link btn btn-primary text-white" %>
    </li>
</li>
<% end %>

<% content_for :dropdown_menu do %>
<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
    <h6 class="dropdown-header">Bienvenue !</h6>
    <div class="dropdown-divider"></div>
    <%= link_to my_properties_path, class: "dropdown-item" do %>
    <i class="fa fa-list fa-lg" aria-hidden="true"></i>&nbsp; Mes annonces
    <% end %>
    <%# if user_signed_in? && current_user.role == "Agent immobilier" %>
    <%#= link_to "Mon agence", edit_agency_path(current_user.agency), class: "dropdown-item" %>
    <%# end %>
    <%= link_to edit_user_registration_path, class: "dropdown-item" do %>
    <i class="fa fa-cog fa-lg" aria-hidden="true"></i>&nbsp; Mon compte
    <% end %>
    <div class="dropdown-divider"></div>
    <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
    <i class="fa fa-sign-out fa-lg" aria-hidden="true"></i>&nbsp;
    Déconnexion
    <% end %>
</div>
<% end %>

<nav class="navbar navbar-expand-lg navbar-light bg-white shadow sticky-top">
    <%= link_to home_page_path, class: "navbar-brand" do %>
    <span class="h3 text-uppercase font-weight-bold">SICO</span>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item mx-1 active">
                <%= link_to home_page_path, class: "nav-link" do %>
                <i class="fa fa-home fa-lg" aria-hidden="true"></i>&nbsp;
                Accueil <span class="sr-only">(current)</span>
                <% end %>
            </li>
            <li class="nav-item mx-1">
                <%= link_to "Toutes les annonces", properties_path, class: "nav-link" %>
            </li>
            <li class="nav-item mx-1 sr-only">
                <%#= link_to "Tout les agents", home_page_path, class: "nav-link" %>
            </li>

            <% if user_signed_in? %>
            <li class="nav-item mx-1">
                <%= link_to my_properties_path, class: "nav-link" do %>
                    <i class="fa fa-list fa-lg" aria-hidden="true"></i>&nbsp;
                    Mes annonces
                <% end %>
            </li>
            <% end %>
        </ul>
        <ul class="navbar-nav ml-auto d-md-flex align-items-md-center">
            <% if user_signed_in? %>
            <% if current_user.profile_picture.attached? %>
            <%= yield :add_property %>
            <li class="nav-item dropdown mx-1">
                <%= link_to "", class: "nav-link dropdown-toggle d-flex align-items-center", id: "navbarDropdown", role: "button", "data-toggle" => "dropdown", "aria-haspopup" => "true", "aria-expanded" => "false" do %>
                <%= image_tag url_for(current_user.profile_picture), size: "30", class: "rounded-circle" %>
                <%= current_user.first_name.capitalize + " " + current_user.last_name.upcase if current_user.first_name.present? && current_user.last_name.present? %>
                <% end %>
                <%= yield :dropdown_menu %>
            </li>
            <% else %>
            <%= yield :add_property %>
            <li class="nav-item dropdown mx-1">
                <%= link_to "", class: "nav-link dropdown-toggle d-flex align-items-center", id: "navbarDropdown", role: "button", "data-toggle" => "dropdown", "aria-haspopup" => "true", "aria-expanded" => "false" do %>
                <i class="fa fa-user-circle fa-2x" aria-hidden="true"></i>&nbsp;
                <%= current_user.first_name.capitalize + " " + current_user.last_name.upcase if current_user.first_name.present? && current_user.last_name.present? %>
                <% end %>
                <%= yield :dropdown_menu %>
            </li>
            <% end %>
            <% else %>
            <%= yield :add_property %>
            <li class="nav-item mx-1">
                <%= link_to "Connexion", new_user_session_path, class: "btn btn-secondary" %>
            </li>
            <% end %>
        </ul>
    </div>
</nav>

app/views/shareds/_vp_for_agent_or_agency.html.erb
<section class="py-5 vp_for_agent_or_agency d-flex align-items-center">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center text-white">
                <!-- <h2>Vous êtes une agence immobilière ?</h2> -->
                <!-- <h3 class="mb-3">Distinguer vous de vos concurrents en promouvant vos offres et services sur <span class="font-weight-bold h3">SICO</span> et atteingnez de nouveaux prospects ou clients.</h3> -->
                <h3>Avez-vous un bien immobilier a vendre ou a louer ?</h3>
                <h4>N'attentez pas, vendez ou louez votre bien aujourd'hui !</h4>
                <p>
                    <%#= link_to "Et si vous essayiez ?", new_property_path, class: "btn btn-primary btn-lg" %>
                    <%= link_to "Créer un compte.", new_user_registration_path, class: "btn btn-primary btn-lg" %>
                </p>
            </div>
        </div>
    </div>
</section>