config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  scope "/(:locale)", locale: /fr/ do

  	root "pages#home", as: "home_page"

    resource :profile

  	resource :agency, only: :show

  	resources :agencies, only: [:index, :show, :edit] do
  		resources :properties
  	end

  	get "agency/benefits", to: "pages#benefits_for_agency", as: "agency_benefits"

  	get "about_us", to: "pages#about_us", as: "about_us"

  	get "contact_us", to: "pages#contact_us", as: "contact_us"

  	get "faq", to: "pages#faq", as: "faq"

  	get "pricing_plan", to: "pages#pricing_plan", as: "pricing_plan"

  	get "terms_and_conditions", to: "pages#terms_and_conditions", as: "terms_and_conditions"

  	post 'properties/:id/publish', to: 'properties#publish', as: "publish_property"

  	post 'properties/:id/deactivate', to: 'properties#deactivate', as: "deactivate_property"

    resources :properties

    resources :messages, only: :create

    resources :contacts, only: :create

    resources :newsletters, only: :create

    scope "/dashboard" do
      resources :my_properties, only: [:index, :edit, :destroy]
    end

  end

end

app/models/ad_type.rb
class AdType < ApplicationRecord
	has_many :properties
end

app/models/agency.rb
class Agency < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    belongs_to :user
    has_many :properties
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :properties
end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :first_name, :last_name, :phone_number, :email, :message, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :user
    validates :name, :phone, :email, :message, :user_id, presence: true
end

app/models/newsletter.rb
class Newsletter < ApplicationRecord
    validates :email, presence: true
    validates :email, uniqueness: { message: "L'adresse email existe déja !" }

    before_save :downcase_email
    # after_save :subscribe

    def downcase_email
        self.email = email.downcase
    end

    # def subscribe
    #     gibbon = Gibbon::Request.new(api_key: Rails.application.secrets.mailchimp_api_key)
    #     list_id = Rails.application.secrets.mailchimp_list_id_key
    #     begin
    #   gibbon.lists(list_id).members.create(
    #   body: {
    #     email: self.email,
    #     status: "subscribed"
    #   })
    # rescue Gibbon::MailChimpError => e
    #   puts "Try Again: #{e.message} ‐ #{e.raw_body}"
    # end
    # end
end

app/models/property.rb
class Property < ApplicationRecord
    extend FriendlyId
    friendly_id :title, use: :slugged

    FEATURE = ["Electricité", "Eau", "WC", "Internet"].sort
    ETAGE = ["Rez-de-chaussée", "1er étage", "2ème étage", "3ème étage", "4ème étage", "5ème étage", "6ème étage", "7ème étage"].sort
    AVAILABLE = { Oui: :TRUE, Nom: :FALSE }

    belongs_to :user
    belongs_to :city
    belongs_to :ad_type
    belongs_to :property_type
    belongs_to :room
    # belongs_to :agency

    validates :price, :description, :address, :area, :title, presence: true
    validates :etage, presence: true, allow_blank: true
    validates :available, presence: true, inclusion: { in: ["TRUE", "FALSE"] }, allow_blank: true
    validates :title, uniqueness: true
    validates :area, numericality: { only_integer: true }
    validates :deposit, numericality: { only_integer: true, greeter_than_or_egal_to: 0 }, allow_blank: true
    validates_associated :user

    has_many_attached :images, dependent: :purge

    scope :published, -> { where(published: true) }
    scope :unpublished, -> { where(published: false) }

    before_save :mettre_tout_en_minuscule
    before_create :definir_la_date_dexpiration
    after_create :suprimer_si_annonce_expire
    # after_destroy :suprimer_les_photos


    private

    def mettre_tout_en_minuscule
        self.title.downcase!
        self.description.downcase!
        self.address.downcase!
    end

    def definir_la_date_dexpiration
        self.published_at = Date.today
        self.expire_at = Date.today + 2.weeks
    end

    def suprimer_si_annonce_expire
        p = Property.find(self.id)
        if p.published? && p.expire_at.past?
            p.delete
        end
    end

    # def suprimer_les_photos
    #     self.images.purge
    # end

end

app/models/property_type.rb
class PropertyType < ApplicationRecord
	has_many :properties
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :properties
end

app/models/user.rb
class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
    devise :confirmable
    devise :omniauthable, omniauth_providers: %i[facebook]

    ROLE = ["Agent immobilier", "Propriétaire"].sort
    GENDER = { M: :Male, F: :Female }

    # validates :role, presence: true, on: :update
    validates :first_name, :last_name, :phone_number, presence: true, on: :update
    validates :phone_number, uniqueness: true, numericality: { only_integer: true }, length: { is: 8 }, on: :update

    # before_create :create_administrator
    after_create :send_welcome_email
    # after_destroy :suprimer_photo_de_profile
    # after_create :build_agency_or_profile

    # has_one :agency, dependent: :delete
    has_many :properties, dependent: :delete_all
    has_many :messages
    has_one_attached :profile_picture, dependent: :purge

    def self.from_omniauth(auth)
        where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
            user.email = auth.info.email
            user.password = Devise.friendly_token[0,20]
            # user.name = auth.info.name   # assuming the user model has a name
            # user.image = auth.info.image # assuming the user model has an image

            user.profile_picture = auth.info.picture
            user.first_name = auth.info.first_name
            user.last_name = auth.info.last_name

            # user.token = auth.credentials.token
            # user.token_expires_at = Time.at(auth.credentials.expires_at)

            # If you are using confirmable and the provider(s) you use validate emails,
            # uncomment the line below to skip the confirmation emails.
            user.skip_confirmation!
        end
    end

    def self.new_with_session(params, session)
        super.tap do |user|
            if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
                user.email = data["email"] if user.email.blank?
            end
        end
    end

    private

    def send_welcome_email
        UserMailer.welcome(self).deliver_now
    end

    # def suprimer_photo_de_profile
    #     self.profile_picture.purge if self.profile_picture.present?
    # end

    def create_administrator
        if self.email == "francel.webdev@gmail.com"
            self.admin = true
        end
    end

    # def build_agency_or_profile
    #   if self.role == "Agent immobilier"
    #       Agency.create user_id: self.id
    #   end
    # end

end

app/controllers/my_properties_controller.rb
class MyPropertiesController < ApplicationController
  def index
      @my_properties = current_user.properties.all.order("created_at DESC").paginate(page: params[:page], per_page: 6)
      @my_properties_numbers = @my_properties.count
  end

  def destroy
      @my_property = Property.find(params[:id])
      @my_property.delete
      redirect_to my_properties_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    skip_before_action :authenticate_user!

    def home

    end

    def contact_us
        @contact = Contact.new
    end

    def faq

    end

    def terms_and_conditions

    end

    def benefits_for_agency

    end

    def benefits_for_owner

    end

    def pricing_plan

    end

end

app/helpers/agencies_helper.rb
module AgenciesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper    
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/my_properties_helper.rb
module MyPropertiesHelper
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/my_properties/index.html.erb
    <% content_for :page_title, "Mes biens" %>

    <section class="container-fluid py-5 my_property-page-banner d-flex flex-column justify-content-center">
        <div class="container">
            <riv class="row">
                <div class="col-lg-12 text-center">
                    <h1 class="text-white">Mes biens</h1>
                </div>
            </riv>
        </div>
    </section>

    <section class="container-fluid py-5">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 mb-4">
                    <%= render "shareds/dashboard_sidebar_menu" %>
                </div>
                <div class="col-lg-8">
                    <div class="row">
                        <div class="col-12">
                            <p>
                                <%= pluralize(@my_properties_numbers, "annonces publié", "annonces publiés") %>
                            </p>
                        </div>

                        <div class="col-12">
                            <div class="row">
                                <% @my_properties.each do |my_property| %>
                                <!-- Grid design -->
                                <div class="col-lg-6 mb-4">
                                    <div class="card result_search_list_design shadow-sm">
                                        <% if my_property.images.attached? %>
                                        <%= image_tag url_for(my_property.images.first), class: "card-img-top", alt: "Photo de #{ my_property.title }" %>
                                        <% else %>
                                        <p class="m-0 d-flex flex-column justify-content-center align-items-center">
                                            <%= image_tag "148705-essential-collection/svg/picture.svg", size: "207x207" %>
                                            <span>Annonce sans photo</span>
                                        </p>
                                        <% end %>

                                        <% if my_property.ad_type.name == "À vendre" %>
                                    <h5 class="position-absolute" style="top: 10px; left: 20px;">
                                        <span class="badge badge-secondary p-2" >À vendre</span>
                                    </h5>
                                    <% elsif my_property.ad_type.name == "À louer" %>
                                    <h5 class="position-absolute" style="top: 10px; left: 20px;">
                                        <span class="badge badge-secondary p-2">À louer</span>
                                        <% end %>
                                    </h5>

                                        <% if my_property.ad_type.name == "Vente" %>
                                        <h5 class="position-absolute" style="top: 10px; left: 20px;">
                                            <span class="badge badge-info p-2">À vendre</span>
                                        </h5>
                                        <% elsif my_property.ad_type.name == "Location" %>
                                        <h5 class="position-absolute" style="top: 10px; left: 20px;">
                                            <span class="badge badge-info p-2">À louer</span>
                                        </h5>
                                        <% end %>

                                        <% if user_signed_in? %>
                                        <% if current_user.admin? and my_property.published %>
                                        <h4><span class="position-absolute badge badge-success p-2" style="top: 10px; right: 10px;">En ligne</span></h4>
                                        <% elsif current_user.admin? and !my_property.published %>
                                        <h4><span class="position-absolute badge badge-warning text-white p-2" style="top: 10px; right: 10px;">En attente de mise en ligne</span></h4>
                                        <% end %>
                                        <% end %>

                                        <div class="card-body">
                                            <h5 class="card-title text-dark">
                                                <%= truncate(strip_tags(my_property.title.capitalize), length: 25) %>
                                            </h5>
                                            <address class="card-text text-secondary">
                                                <i class="fa fa-map-marker fa-lg" aria-hidden="true"></i>&nbsp; <%= my_property.address %>, <%= my_property.city.name %>
                                            </address>
                                            <% if my_property.ad_type.name == "À vendre" %>
                                            <p class="text-primary m-0 p-0 h3">
                                                <%= number_to_currency(my_property.price, precision: 0) %>
                                            </p>
                                            <% elsif my_property.ad_type.name == "À louer" %>
                                            <p class="text-primary m-0 p-0 h3">
                                                <%= number_to_currency(my_property.price, precision: 0) %>/mois
                                            </p>
                                            <% end %>
                                            <hr>
                                            <div class="d-flex justify-content-between align-items-center mb-0">
                                            <p class="mb-0">
                                                <small class="text-dark">Publié il y a <%= distance_of_time_in_words(my_property.created_at, Time.now, include_seconds: false) %></small>
                                            </p>
                                            <div class="btn-group" role="group" aria-label="Basic example">
                                                <%= link_to "Modifier", edit_property_path(my_property), class: "btn btn-primary" %>
                                                <%= link_to "Voir", my_property, class: "btn btn-primary" %>
                                            </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- Grid design -->
                                <% end %>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>